FLASK_ENV=development
FLASK_DEBUG=1
FLASK_HOST=0.0.0.0
FLASK_PORT=5000
FLASK_APP=wsgi.py
#FLASK_APP=app.py

#import these manually in your config.py file
#DATABASE_URL=None
EXPLAIN_TEMPLATE_LOADING=True
SQLALCHEMY_ECHO = True
SQLALCHEMY_TRACK_MODIFICATIONS = True
TEMPLATES_AUTO_RELOAD=True
TESTING=True
